### PR TITLE
Fix incorrect link

### PR DESCRIPTION
**Pull request by eahlberg**

### CODE REVIEW

**Comment by eahlberg** [comment]
@snoyberg first off, thanks for a good site! 🙇‍♂️

When I was reading through the `Promote` section I found a dead link, which seems to be available at a new domain. If you can confirm that this actually is the same article, I'll mark this draft PR as ready for review.

**Comment by snoyberg** [comment]
Thanks for catching these!

Looks right, but to be honest I'm not sure. I copied the content over from haskell-lang, and don't remember checking that link in the first place. Looks like a good update to me.

**Comment by eahlberg** [comment]
ok, cool!

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
